app/views/detail_views.py
from flask import Blueprint, url_for, render_template, request, redirect, flash
from flask_login import login_user, current_user, logout_user, login_required

from app.forms import LoginForm, QuestionForm, FaqForm
from app.models import User, Question, Question_A, Answer, Comment, Faq
from app import db


from datetime import datetime

bp = Blueprint("detail", __name__, url_prefix="/detail")


@bp.route("/faq")
def faq_list():
    faq_list = Faq.query.order_by(Faq.id.desc()).all()
    return render_template("faq_list.html", faq_list=faq_list)


@bp.route("/question")
def question_list():
    page = request.args.get("page", type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template(
        "question/question_list.html", question_list=question_list
    )


@bp.route("/question_detail/<int:question_id>", methods=["GET", "POST"])
def question_detail(question_id):
    question = Question.query.get(question_id)
    if request.method == "POST":
        db.session.delete(question)
        db.session.commit()
        return redirect(url_for("detail.question_list"))
    return render_template("question/question_detail.html", question=question)


@bp.route("/question_create", methods=["GET", "POST"])
@login_required
def question_create():
    form = QuestionForm()
    if request.method == "POST" and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        question = Question(
            subject=subject,
            content=content,
            create_date=datetime.now(),
            user_id=current_user.get_id(),
        )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for("detail.question_list"))

    return render_template("question/question_create.html", form=form)


@bp.route("/login_required", methods=["GET", "POST"])
def login_required():
    form = LoginForm()
    if request.method == "POST" and form.validate_on_submit():
        id = form.id.data
        pw = form.pw.data
        user = User.query.filter_by(id=id).first()
        if user.pw == pw:
            login_user(user)
            flash("로그인 성공!")
            return redirect(url_for("main.main"))
        else:
            flash("계정 정보가 일치하지 않습니다")
            return redirect(url_for("main.main"))
    return render_template("login_required.html", form=form)


@bp.route("/anonymous_list")
def anonymous():
    page = request.args.get("page", type=int, default=1)
    question_list = Question_A.query.order_by(Question_A.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template(
        "question/question_a_list.html", question_list=question_list
    )


@bp.route("/anonymous_detail/<int:question_id>", methods=["GET", "POST"])
def a_detail(question_id):
    question = Question_A.query.get(question_id)
    if request.method == "POST":
        db.session.delete(question)
        db.session.commit()
        return redirect(url_for("detail.anonymous"))
    return render_template("question/question_a_detail.html", question=question)


@bp.route("/question_a_create", methods=["GET", "POST"])
def question_a_create():
    form = QuestionForm()
    if request.method == "POST" and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        question = Question_A(
            subject=subject, content=content, create_date=datetime.now()
        )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for("detail.anonymous"))

    return render_template("question/question_a_create.html", form=form)


@bp.route("/answer/<int:question_id>", methods=["POST"])
def answer(question_id):
    if request.method == "POST":
        print("gd")
        content = request.form["answer"]
        print(content)
        question_id = question_id
        answer = Answer(
            question_id=question_id, content=content, create_date=datetime.now()
        )
        db.session.add(answer)
        db.session.commit()
        return redirect(
            url_for("detail.question_detail", question_id=question_id)
        )
    else:
        return "잘못된 접근입니다."


@bp.route("/answer_delete/<int:answer_id>")
def answer_delete(answer_id):
    answer = Answer.query.get(answer_id)
    question_id = answer.question_id
    db.session.delete(answer)
    db.session.commit()
    return redirect(url_for("detail.question_detail", question_id=question_id))


@bp.route("comment/<int:question_id>", methods=["POST"])
def comment_create(question_id):
    if request.method == "POST":
        content = request.form["comment"]
        comment = Comment(
            question_a_id=question_id,
            content=content,
            create_date=datetime.now(),
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("detail.a_detail", question_id=question_id))


@bp.route("/comment_delete/<int:comment_id>")
def comment_delete(comment_id):
    comment = Comment.query.get(comment_id)
    question_id = comment.question_a_id
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("detail.a_detail", question_id=question_id))


@bp.route("/faq_create", methods=["GET", "POST"])
def faq_create():
    form = FaqForm()
    if request.method == "POST" and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        faq = Faq(subject=subject, content=content)
        db.session.add(faq)
        db.session.commit()
        return redirect(url_for("detail.faq_list"))
    return render_template("faq_create.html", form=form)


@bp.route("/faq_modify/<int:faq_id>", methods=["GET", "POST"])
def faq_modify(faq_id):
    faq = Faq.query.get(faq_id)
    if request.method == "POST":
        faq.subject = request.form["subject"]
        faq.content = request.form["content"]

        db.session.commit()
        return redirect(url_for("detail.faq_list"))
    return render_template("faq_create.html", faq=faq)

app/templates/question/question_a_create.html
{% extends 'base.html' %}

{%block contents %}

<section class="inner">
  <h2>질문 등록하기</h2>
  <hr>
  <br>
  {% for field, errors in form.errors.items() %}
  <div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
  </div>
  {% endfor %}
  <form method="POST">
    {{form.csrf_token}}
    <div class="form-floating">
      <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea" name="subject"></textarea>
      <label for="floatingTextarea">제목</label>
    </div>
    <br>
    <div class="form-floating">
      <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height:500px;"
        name="content"></textarea>
      <label for="floatingTextarea2">내용</label>
    </div>
    <button type="submit" class="btn btn-outline-secondary" style="margin-top: 20px;">등록하기</button>
  </form>
</section>

{%endblock%}

app/templates/question/question_a_detail.html
{% extends 'base.html' %}

{%block contents %}
<section class="inner">
  <h3 style="margin-top: 100px; margin-bottom: 20px;">익명 자유 게시판</h3>

  <h6>[아쉽게도 어떤 방법으로도 확인이 불가능하니, 안심하고 써도 됩니다^^ 하고싶은 말 다 해보세요]</h6>
  {% if question %}
  <div class="card">
    <div class="card-body container">
      <div class="row justify-content-end"> <small>작성일시: {{question.create_date|datetime}}</small>
      </div>

      <div class="row align-items-center">
        <h5>{{question.subject}}</h5>
      </div>

    </div>
  </div>
  <div class="card" style="height:600px; margin-top: 20px;">
    <div class="card-body">
      <small>본문</small>
      <p>{{question.content}}</p>
    </div>
  </div>
  {% endif %}
  {%if current_user.id ==8171%}
  <br>
  <form method="POST">
    <button type="submit" class="btn btn-secondary">삭제하기</button>
  </form>

  {%endif%}
  <a class="btn btn-outline-secondary my-2" href="{{ url_for('detail.anonymous') }}" role="button">목록으로
    돌아가기</a>

  {% if question.comment_set%}
  <h5>[ 댓글 ]</h5>
  {% for comment in question.comment_set %}
  <div class="card my-2 p-2">
    <div class="card-body container">
      <div class="row justify-content-center">
        <div class="col-10"></div>
        <div class="col-2">{{comment.create_date|datetime}}</div>
      </div>
      <div class="row">
        <div class='col-10'>{{comment.content}}</div>
      </div>
      {% if current_user.id == 8171 %}
      <div class="row">
        <a href="{{ url_for('detail.comment_delete', comment_id = comment.id )}}" class='small'>
          <small>삭제하기</small>
        </a>
      </div>
      {% endif %}


    </div>
  </div>
  {%endfor%}
  {%endif%}

  <form action="{{url_for('detail.comment_create',question_id=question.id)}}" method='POST' style="margin-top: 20px;">
    <div class="mb-3">
      <label for="comment" class="form-label">댓글 작성하기</label>
      <textarea class="form-control" id="comment" rows="2" name="comment"></textarea>
    </div>
    <button type="submit" class="btn btn-secondary">등록</button>
  </form>
</section>


{%endblock%}

app/templates/question/question_a_list.html
{% extends 'base.html' %}

{% block contents %}
<section class="inner">
  <h1>익명 자유 게시판</h1>
  <h5 style="color: red;"> [ 타인에 대한 비방은 자제합시다! ] </h5>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">제목</th>
        <th scope="col">작성일자</th>
        <th scope="col">댓글수</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %}
      {%for question in question_list.items %}
      <tr onclick="location.href='/detail/anonymous_detail/{{question.id}}'">
        <th scope="row">{{loop.index}}</th>
        <td>{{question.subject}}</td>
        <td>{{question.create_date|datetime}}</td>
        <td>{{question.comment_set|length}}</td>
      </tr>
      {%endfor%}
      {%else%}
      <tr>
        <td>질문이 없습니다</td>
      </tr>
      {%endif%}
    </tbody>
  </table>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_prev %}
    <li class="page-item">
      <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in question_list.iter_pages() %}
    {% if page_num %}
    {% if page_num != question_list.page %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">{{ page_num }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled">
      <a class="page-link" href="#">...</a>
    </li>
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
  <a class="btn btn-outline-secondary" href="{{url_for('detail.question_a_create') }}" role="button">질문 작성하기</a>
</section>
{% endblock %}

app/templates/question/question_create.html
{% extends 'base.html' %}

{%block contents %}

<section class="inner">
  <h2>질문 등록하기</h2>
  <hr>
  <br>
  {% for field, errors in form.errors.items() %}
  <div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
  </div>
  {% endfor %}
  <form method="POST">
    {{form.csrf_token}}
    <div class="form-floating">
      <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea" name="subject"></textarea>
      <label for="floatingTextarea">제목</label>
    </div>
    <br>
    <div class="form-floating">
      <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height:500px;"
        name="content"></textarea>
      <label for="floatingTextarea2">내용</label>
    </div>
    <button type="submit" class="btn btn-outline-secondary" style="margin-top: 20px;">등록하기</button>
  </form>
</section>

{%endblock%}

app/templates/question/question_detail.html
{% extends 'base.html' %}

{%block contents %}
<section class="inner">
  <h3 style="margin-top: 100px; margin-bottom: 20px;">건의&QnA 게시판</h3>
  {% if question %}
  <div class="card">
    <div class="card-body">
      <h4>{{question.subject}}</h4>
      <small>작성자: {{question.user.name}}</small>
    </div>
  </div>
  <div class="card" style="height:600px; margin-top: 20px;">
    <div class="card-body">
      <p>{{question.content}}</p>
    </div>
  </div>
  {% endif %}
  {%if current_user.id == question.user_id or current_user.id == 8171%}
  <br>
  <form method="POST">
    <button type="submit" class="btn btn-secondary">삭제하기</button>
  </form>

  {%endif%}
  <a class="btn btn-outline-secondary my-2" href="{{ url_for('detail.question_list') }}" role="button">목록으로
    돌아가기</a>
  {% if question.answer_set %}
  <h4>답변</h4>
  {% for answer in question.answer_set %}
  <div class="card my-2 p-2">
    <div class="card-body">
      {{answer.content}}
    </div>
    {%if current_user.id == 8171 %}
    <div>
      <a href="{{ url_for('detail.answer_delete', answer_id = answer.id )}}" class='small'>
        <small>삭제하기</small>
      </a>
    </div>
    {% endif %}
  </div>
  {% endfor %}
  {%else%}
  <h4>아직 답변이 등록되지 않았어요</h4>
  {%endif%}

  {% if current_user.id == 8171 %}
  <br>
  <br>
  <form action="{{ url_for('detail.answer', question_id=question.id) }}" method='POST'>
    <div class="mb-3">
      <label for="answer" class="form-label">[ 답변하기 ]</label>
      <textarea class="form-control" id="answer" rows="4" name='answer'></textarea>
    </div>
    <button type="submit" class="btn btn-secondary">등록</button>
  </form>
  {%endif%}
</section>


{%endblock%}

app/templates/question/question_list.html
{% extends 'base.html' %}

{%block contents %}
<section class="inner">
  <h1>건의&QnA 게시판</h1>
  <ul>
    <li><span>요령</span> : 문제 상황을 구체적으로 기술해주세요</li>
    <li><span>건의 예시</span>: 청소도구 부족, 시설 고장, 제도적 건의 사항</li>
    <li><span>QnA 예시</span>: @@지침이 애매한데, 정확히 뭔가요?</li>
    <li><span>QnA 예시</span>: 군생활 꿀팁이 있을까요?</li>
    <li><span></span>훈련대원이 확인하고 하루 이내로 답변을 달고 조치를 취해주도록 할게요</li>
    <li><span style="color: red;">훈련대원 개인의 의견이고, 잘못 알고 있는 경우에는 책임지지 않습니다. 참고용으로만 파악하고 다시 본인이 확인할 수 있도록 합니다</span></li>

  </ul>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">작성자</th>
        <th scope="col">제목</th>
        <th scope="col">작성일자</th>
        <th scope='col'>답변</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %}
      {%for question in question_list.items %}
      <tr onclick="location.href='/detail/question_detail/{{question.id}}'">
        <th scope="row">{{loop.index}}</th>
        <td>{{question.user.name}}</td>
        <td>{{question.subject}}</td>
        <td>{{question.create_date|datetime}}</td>
        <td>{% if question.answer_set %}O {%else%}X{%endif%}</td>
      </tr>
      {%endfor%}
      {%else%}
      <tr>
        <td>질문이 없습니다</td>
      </tr>
      {%endif%}
    </tbody>
  </table>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_prev %}
    <li class="page-item">
      <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in question_list.iter_pages() %}
    {% if page_num %}
    {% if page_num != question_list.page %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">{{ page_num }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled">
      <a class="page-link" href="#">...</a>
    </li>
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
  <a class="btn btn-outline-secondary" href="{{url_for('detail.question_create') }}" role="button">질문 작성하기</a>
</section>

{% endblock %}