app/views/detail_views.py
from flask import Blueprint, url_for, render_template, request, redirect, flash
from flask_login import login_user, current_user, logout_user, login_required

from app.forms import LoginForm, QuestionForm, FaqForm
from app.models import User, Question, Question_A, Answer, Comment, Faq
from app import db


from datetime import datetime

bp = Blueprint("detail", __name__, url_prefix="/detail")


@bp.route("/faq")
def faq_list():
    faq_list = Faq.query.order_by(Faq.id.desc()).all()
    return render_template("faq_list.html", faq_list=faq_list)


@bp.route("/question")
def question_list():
    page = request.args.get("page", type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template(
        "question/question_list.html", question_list=question_list
    )


@bp.route("/question_detail/<int:question_id>", methods=["GET", "POST"])
def question_detail(question_id):
    question = Question.query.get(question_id)
    if request.method == "POST":
        db.session.delete(question)
        db.session.commit()
        return redirect(url_for("detail.question_list"))
    return render_template("question/question_detail.html", question=question)


@bp.route("/question_create", methods=["GET", "POST"])
@login_required
def question_create():
    form = QuestionForm()
    if request.method == "POST" and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        question = Question(
            subject=subject,
            content=content,
            create_date=datetime.now(),
            user_id=current_user.get_id(),
        )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for("detail.question_list"))

    return render_template("question/question_create.html", form=form)


@bp.route("/login_required", methods=["GET", "POST"])
def login_required():
    form = LoginForm()
    if request.method == "POST" and form.validate_on_submit():
        id = form.id.data
        pw = form.pw.data
        user = User.query.filter_by(id=id).first()
        if user.pw == pw:
            login_user(user)
            flash("로그인 성공!")
            return redirect(url_for("main.main"))
        else:
            flash("계정 정보가 일치하지 않습니다")
            return redirect(url_for("main.main"))
    return render_template("login_required.html", form=form)


@bp.route("/anonymous_list")
def anonymous():
    page = request.args.get("page", type=int, default=1)
    question_list = Question_A.query.order_by(Question_A.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template(
        "question/question_a_list.html", question_list=question_list
    )


@bp.route("/anonymous_detail/<int:question_id>", methods=["GET", "POST"])
def a_detail(question_id):
    question = Question_A.query.get(question_id)
    if request.method == "POST":
        db.session.delete(question)
        db.session.commit()
        return redirect(url_for("detail.anonymous"))
    return render_template("question/question_a_detail.html", question=question)


@bp.route("/question_a_create", methods=["GET", "POST"])
def question_a_create():
    form = QuestionForm()
    if request.method == "POST" and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        question = Question_A(
            subject=subject, content=content, create_date=datetime.now()
        )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for("detail.anonymous"))

    return render_template("question/question_a_create.html", form=form)


@bp.route("/answer/<int:question_id>", methods=["POST"])
def answer(question_id):
    if request.method == "POST":
        print("gd")
        content = request.form["answer"]
        print(content)
        question_id = question_id
        answer = Answer(
            question_id=question_id, content=content, create_date=datetime.now()
        )
        db.session.add(answer)
        db.session.commit()
        return redirect(
            url_for("detail.question_detail", question_id=question_id)
        )
    else:
        return "잘못된 접근입니다."


@bp.route("/answer_delete/<int:answer_id>")
def answer_delete(answer_id):
    answer = Answer.query.get(answer_id)
    question_id = answer.question_id
    db.session.delete(answer)
    db.session.commit()
    return redirect(url_for("detail.question_detail", question_id=question_id))


@bp.route("comment/<int:question_id>", methods=["POST"])
def comment_create(question_id):
    if request.method == "POST":
        content = request.form["comment"]
        comment = Comment(
            question_a_id=question_id,
            content=content,
            create_date=datetime.now(),
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("detail.a_detail", question_id=question_id))


@bp.route("/comment_delete/<int:comment_id>")
def comment_delete(comment_id):
    comment = Comment.query.get(comment_id)
    question_id = comment.question_a_id
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("detail.a_detail", question_id=question_id))


@bp.route("/faq_create", methods=["GET", "POST"])
def faq_create():
    form = FaqForm()
    if request.method == "POST" and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        faq = Faq(subject=subject, content=content)
        db.session.add(faq)
        db.session.commit()
        return redirect(url_for("detail.faq_list"))
    return render_template("faq_create.html", form=form)


@bp.route("/faq_modify/<int:faq_id>", methods=["GET", "POST"])
def faq_modify(faq_id):
    faq = Faq.query.get(faq_id)
    if request.method == "POST":
        faq.subject = request.form["subject"]
        faq.content = request.form["content"]

        db.session.commit()
        return redirect(url_for("detail.faq_list"))
    return render_template("faq_create.html", faq=faq)

app/views/main_views.py
from flask import (
    Blueprint,
    url_for,
    render_template,
    request,
    redirect,
    flash,
    session,
)
from flask_login import login_user, current_user, logout_user, login_required

from app.models import User, Question, Question_A, Faq
from app.forms import LoginForm

bp = Blueprint("main", __name__, url_prefix="/")


@bp.route("/")
def to_main():
    return redirect(url_for("main.main"))


@bp.route("/main", methods=["GET", "POST"])
def main():
    form = LoginForm()
    faq_list = Faq.query.limit(4).all()
    question_list = (
        Question.query.order_by(Question.create_date.desc()).limit(4).all()
    )
    question_a_list = (
        Question_A.query.order_by(Question_A.create_date.desc()).limit(4).all()
    )
    if form.validate_on_submit():
        id = form.id.data
        pw = form.pw.data
        user = User.query.filter_by(id=id).first()
        if user.pw == pw:
            login_user(user)
            flash("로그인 성공!")
            return redirect(url_for("main.main"))
        else:
            flash("계정 정보가 일치하지 않습니다")
            return redirect(url_for("main.main"))
    return render_template(
        "main.html",
        form=form,
        question_list=question_list,
        question_a_list=question_a_list,
        faq_list=faq_list,
    )


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.main"))


@bp.route("/test")
def test():
    return str(request.environ)

app/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0">
  <title>교육훈련센터 게시판</title>

  <!-- Open Graph -->
  <meta property="og:type" content="website">
  <meta property="og:title" content="교육훈련센터 게시판">
  <meta property="og:description" content="질문을 등록하고 답변을 받으세요">
  <meta property="og:image" content="/app/static/img/og_main.PNG">

  <!-- CSS Rest 설정 값 초기화 -->
  <link rel='stylesheet' href="{{url_for('static', filename='css/normalize.css')}}">

  <!-- 각종 아이콘 가져오기 -->
  <script src="https://kit.fontawesome.com/622b3fccfe.js" crossorigin="anonymous"></script>

  <!-- 웹폰트 가져오기 : Spoca Han Sans Neo -->
  <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css' rel='stylesheet' type='text/css'>

  <!-- 부트스트랩 css 파일 -->
  <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">

  <!-- 직접 만든 css 파일 -->
  <link rel='stylesheet' href="{{url_for('static',filename='css/style.css')}}">
</head>

<body>
  <header>
    {% include 'nav.html' %}
  </header>
  {% block contents %}
  {% endblock %}

</body>

</html>

app/templates/faq_create.html
{% extends 'base.html' %}

{%block contents %}

<section class="inner">
  <h2>FAQ 만들기</h2>
  <hr>
  <br>
  <form method="POST">
    <div class="form-floating">
      <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea"
        name="subject">{{ faq.subject or '' }}</textarea>
      <label for="floatingTextarea">제목</label>
    </div>
    <br>
    <div class="form-floating">
      <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height:500px;"
        name="content">{{faq.content or ''}}</textarea>
      <label for="floatingTextarea2">내용</label>
    </div>
    <button type="submit" class="btn btn-outline-secondary" style="margin-top: 20px;">등록하기</button>
  </form>
</section>

{%endblock%}

app/templates/faq_list.html
{% extends 'base.html' %}

{% block contents %}
<section class='inner faq_table'>
  <h1>FAQ</h1>
  <h3 style="color: red;">현재 실제 시행 내용과 약간 다를 수 있습니다.</h3>
  <h5 style="color: red;">다른 내용에 대해서는 책임지지 않습니다</h5>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
      {% for faq in faq_list %}
      <tr>
        <td>
          <div>
            <label for="{{faq.id}}" class="toggle_button">{{faq.subject}}</label>
            <input type="checkbox" id="{{faq.id}}">
            <div id="toggle_contents" style="white-space: pre-line;">
              {{faq.content}}
              <div>
                <a class='btn btn-primary my-3' href="{{url_for('detail.faq_modify', faq_id=faq.id)}}">faq 수정하기</a>
              </div>
              <label for="toggle_button3" class="close_button">X</label>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>
  {% if current_user.id == 8171 %}
  <a class='btn btn-primary my-3' href="{{url_for('detail.faq_create')}}">faq 작성하기</a>


  {% endif %}
</section>
{%endblock%}

app/templates/login_required.html
{%extends 'base.html' %}

{%block contents%}
<section class="inner" id='only_login'>


  <div class="login_form login_required">
    <h5>로그인 없이는 <br>접근이 불가능합니다</h5>
    <form method="POST">
      {{form.csrf_token}}
      <div class="form-floating">
        {{ form.id(class=' form-control login_input', id='floatingInput' )}} {{ form.id.label(for="floatingInput" )}}
      </div>
      <div class="form-floating">
        <input type="password" class="form-control login_input" id="floatingInput" name='pw'>
        <label for="floatingInput">PASSWORD</label>
      </div>
      <button type="submit" id='button' class='btn btn-outline-secondary'>로그인하기</button>
    </form>
  </div>
</section>
{%endblock%}

app/templates/main.html
{% extends 'base.html' %}

{%block contents%}
<section class="main_img">
    <div class="main_container inner">
        <div class="title_container">
            <div class="title">1139기 교육생 여러분 환영합니다</div>
            <div class="message">3주간의 교육 기간 동안 여러분이 <br>
                자랑스러운 대한민국 의경으로 거듭나길 바랍니다.<br>
                이곳의 기억이 길고 힘든 군생활동안 가슴 속에 품고 있을 만큼<br>
                의미 있는 시작점이 되길 바랍니다.
            </div>
        </div>
    </div>
</section>
<section class='first_main inner'>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {%for message in messages %}
    <h3>{{message}}</h3>
    {%endfor%}
    {%endif%}
    {%endwith%}
    <div class="login_form">
        {% if current_user.is_authenticated %}
        <h2>안녕하세요</h2>
        <h5>{{current_user.name}}</h5>
        <a class='btn btn-outline-secondary' href="{{url_for('main.logout')}}">로그아웃하기</a>
        {%else%}
        </form>
        <h6>*질문을 작성하려면 로그인하세요!</h6>
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <form method="POST">
            {{form.csrf_token}}
            <div class="form-floating">
                {{form.id(class='form-control login_input', id='floatingInput')}}
                {{form.id.label(for="floatingInput")}}
            </div>
            <div class="form-floating">
                <input type="password" class="form-control login_input" id="floatingInput" name='pw'>
                <label for="floatingInput">PASSWORD</label>
            </div>
            <button type="submit" id='button' class='btn btn-outline-secondary'>로그인하기</button>
        </form>
        {%endif%}
    </div>
    <div class="updown"></div>
    <div class="faq_container">
        <h2>FAQ</h2>
        <hr>

        <div class="faq_list">
            {% for faq in faq_list %}
            <a href="{{url_for('detail.faq_list')}}">
                <div class="faq_card">
                    <div class="card_title">{{faq.subject}}</div>
                    <hr>
                    <div class="card_detail">
                        {{faq.content}}
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
    </div>
</section>
<section class="inner">
    <h2>건의&QnA 게시판</h2>
    <h6 style="color: red;">*로그인이 필요합니다</h6>
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">작성자</th>
                <th scope="col">제목</th>
                <th scope="col">작성일자</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {%for question in question_list %}
            <tr onclick="location.href='/detail/question_detail/{{question.id}}'">

                <th scope="row">{{loop.index}}</th>
                <td>{{question.user.name}}</td>
                <td>{{question.subject}}
                </td>
                <td>{{question.create_date|datetime}}</td>
                </a>
            </tr>

            {%endfor%}
            {%endif%}
        </tbody>
    </table>
    <a class="btn btn-outline-secondary mb-2" href="{{ url_for('detail.question_list') }}" role="button">목록 보기</a>
</section>
<section class="inner">
    <h2>익명 자유 게시판</h2>
    <h6 style="color: red;">*로그인이 필요하지 않습니다</h6>
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">제목</th>
                <th scope="col">작성일자</th>
            </tr>
        </thead>
        <tbody>
            {% if question_a_list %}
            {%for question in question_a_list %}
            <tr onclick="location.href='/detail/anonymous_detail/{{question.id}}'">
                <th scope="row">{{loop.index}}</th>
                <td>{{question.subject}}</td>
                <td>{{question.create_date|datetime}}</td>
            </tr>
            {%endfor%}
            {%endif%}
        </tbody>
    </table>
    <a class="btn btn-outline-secondary mb-2" href="{{ url_for('detail.anonymous') }}" role="button">목록 보기</a>
</section>
<section class="footer">
    <div>
        <div>
            이 사이트는 교육생들을 위해 훈련대원의 자발적인 선의로 만들어졌습니다.
        </div>
        <div><small>
                그러므로 위 사이트의 내용에 대해 일체의 책임을 지지 않습니다.
            </small></div>
        <div>
            Copyright by 훈련대원 박민준
        </div>
    </div>

</section>

{% endblock %}

app/templates/nav.html
<nav class='inner'>
  <div>
    <a href="{{ url_for('main.main') }}">메인화면</a>
  </div>
  {%if current_user.is_authenticated %}
  <div>
    <a href="{{url_for('main.logout')}}">{{current_user.name}}<small> 로그아웃</small></a>
  </div>
  {% endif %}
</nav>